### PR TITLE
Joshua Clements - Final

### PR DESCRIPTION
**Pull request by joshuayclements**
Hey guys, can you please check out my work @kalenakudelima @sam-campos .

Here is a link to the site
http://joshuayclements.github.io/final-1/examples/todo/

### CODE REVIEW

**Comment by sam-campos** [comment]
bravo! this is super good dude!!!!!!!!! wow!

**Comment by kalenakudelima** [comment]
Super clean! Looks really good. I learned something new too: "visibility: visible;" & "visibility: hidden;". I didn't know that was a thing! So SASSy....get it? lol! Nice work.

**Comment by joshuayclements** [comment]
thank you @sam-campos and @kalenakudelima 

@micjamking Final Critique

**Comment by micjamking** [comment]
Nice job Josh!

**Pull request closed without merging**
